TX_NEW vs TX_NET_NEW
---
  
  Load R Packages
```{r message=FALSE}
library(tidyverse)
library(scales)
library(lubridate)
library(RColorBrewer)
```

Read data

```{r message=FALSE}
txData <- read_csv("https://raw.githubusercontent.com/USAID-OHA-SI/coRps/master/2020-03-30/FY20_MilkyWay_NewtoNetNew.csv")
```

Explore the content of data

```{r}
txData %>% str()
```

```{r}
txData %>% glimpse()

```

```{r}
txData %>% 
  distinct(fiscal_year, operatingunit, fundingagency, primepartner)
```

Visualization

```{r}
coef(lm(TX_NEW ~ TX_NET_NEW, data = txData))

txData %>% 
  ggplot(aes(TX_NEW, TX_NET_NEW)) +
  geom_point(aes(color = fundingagency), shape = 16, size = 6, alpha = .5) +
  geom_hline(yintercept = 0, color = 'gray10') +
  geom_vline(xintercept = 0, color = 'gray10') +
  geom_smooth(method = "lm", se = FALSE) +
  scale_colour_manual(values = c('gray60', 'gray30', 'purple')) +
  labs(title = "HIV Treatments",
       subtitle = "Newly enrolled in ART",
       caption = "USAID's Office of HIV/AIDS") +
  theme_minimal()
```